NKI-AI/dlup

dlup/_image.py, dlup/experimental_backends/_pyvips.py, dlup/experimental_backends/_tifffile.py
=> fix unit_dict in _read_as_tiff

dlup/_image.py, dlup/experimental_backends/_tifffile.py
- Enable to set backend by string
- Fix when there are empty tiles
=> Fix some TIGER tiffs

dlup/data/dataset.py, dlup/data/experimental/dataset.py, dlup/experimental_annotations.py
=> Extend annotations (#83)

dlup/data/dataset.py, dlup/experimental_annotations.py, tests/test_annotations.py, tools/README.md, tools/convert_tiger_to_tcga.py, tools/write_annotated_roi_to_file.py
Annotations can now be read with a given scaling factor and exported to GeoJSON
=> Export GeoJSON and support scaling

dlup/experimental_annotations.py, tools/convert_tiger_to_tcga.py
Allow to remap labels when reading
=> Remap labels

dlup/data/dataset.py, dlup/data/experimental/dataset.py, dlup/data/transforms.py, dlup/experimental_annotations.py
- ROIs should be given at level zero
- ROI output of transform now correct
=> Fixes for ROI in datasets

dlup/_region.py
=> Allow L regions

dlup/data/dataset.py
This fixes the issue that a SlideImage currently cannot be used as an annotation
=> Fix SlideImage as annotation

dlup/data/dataset.py
=> Made `self.transform` a private member in the base classes.

dlup/data/dataset.py, dlup/data/transforms.py
This fixes an error when a Multipolygon of polygons is not always valid
=> Ensure multipolygon is always valid

dlup/annotations.py, dlup/data/transforms.py
=> points annotation conversion hotfix

dlup/_image.py, dlup/annotations.py
This fixes the ability to load geojsons with `MultiPolygon` structures (and improving some typing)
=> Fix multiplier

dlup/data/dataset.py
This issue allows to use a different output tile size than the underlying grid. Given a grid, the tile will be extracted around the center of the grid element.
=> Different tile size in the grid

dlup/annotations.py, setup.py
Now we can call `bounding_box` on an instance of `WsiAnnotations`.
=> Add property to compute the bounding box of `WsiAnnotations`

dlup/_region.py, dlup/writers.py
TiffWriter should also have possibility to set a different interpolation
=> Allow to select a different interpolator in TiffWriter

dlup/annotations.py
=> Support multipoint

.dev/bump_date.py, dlup/data/transforms.py
Implement a functional interface for RenameLabels, useful in ahcore (typing)
=> Implement functional interface for RenameLabels

dlup/data/dataset.py
Somewhere along the history of dlup, the output_tile_size was removed from the dataset. This is an important parameter if we want to sample a large variety of tiles from a given WSI. I reinsert this feature from a past version. [Here](https://github.com/NKI-AI/dlup/blob/c6bbf1c57498dbcc29203fbf538ce85b2accb545/dlup/data/dataset.py#L176), you can find it.
=> Add `output_tile_size` parameter to BaseWsiDataset

dlup/annotations.py
Urgent fix, it's a bug introduced after making Darwin work. This bug was introduced in https://github.com/NKI-AI/dlup/pull/162
=> Fix sorting

dlup/data/dataset.py, dlup/data/transforms.py, tests/test_logging.py, tests/test_transforms.py
convert_annotations now has a test coverage of 100%
=> Added complete tests for convert_annotations

dlup/cli/mask.py, dlup/experimental_backends/pyvips_backend.py
=> Implement ICC profile in the pyvips backend
